### ISSUE TITLE
Following the exact instructions leads to a compilation error

### ISSUE THREAD

**Issue by nigelbabu** [gluster/gluster-block#124] opened 2018-10-03 07:47 UTC
The instructions in the README.me leaves me with this error on Fedora 28:

```
libtool: compile:  gcc -DHAVE_CONFIG_H -g -O2 -MT block_clnt.lo -MD -MP -MF .deps/block_clnt.Tpo -c block_clnt.c  -fPIC -DPIC -o .libs/block_clnt.o
In file included from block_clnt.c:7:
block.h:9:10: fatal error: rpc/rpc.h: No such file or directory
 #include <rpc/rpc.h>
          ^~~~~~~~~~~
compilation terminated.
```

**Comment by pkalever** [comment] 2018-10-03 07:49
Duplicate of https://github.com/gluster/gluster-block/issues/56

**Closed** 2018-10-03 07:49 UTC
