### ISSUE TITLE
gluster-block need the ALUA feature to support the HA.

### ISSUE THREAD

**Issue by lxbsz** [gluster/gluster-block#53] opened 2018-03-14 10:20 UTC
The alua is a must for gluster-block, because due to the design of the LIO & tcmu, if one path has been blocked for a long time (such as due to the network's reason) then the IO requests on the client side will time-out and try to resend the IO requests through the other available path(HA). Just then if the blocked path recover and if it continue the old IO requests to the backend, then we are prone to overwrite or data crash issues.

NOTE:
=====================
Lock Type:
1，An exclusive-lock is needed

Important APIs:
1, glfs_block_lock_get_owners(): One way to get the current owner of the exclusive-lock of the file backend.
2, glfs_block_is_exclusive_lock_owner()：One way to check whether the current target in current node is the owner.
3, glfs_block_lock_break(): Try to break the lock owned by one target in another node.
4, glfs_block_lock_acquire(): Try to acquire the lock and to be the lock owner.
5, ....

The tcmu's framework about ALUA's implementing is :
1, If the ALUA is enabled and used, the multipath actually is in AP mode here, the tcmu is just using the ALUA proto to support failover feature, that's all.
2, Only one path could be used and keep alive at a time as we know for the AP mode.
3, If the Active path, in nodeA for example, is timed out or died, the multipath in client side will try another one, nodeB.
4, The nodeB will try to get the owner of the lock and then breaks it, if it is successful then try to acquire the lock.
5, If every thing is okay in nodeB, then the path will be switched to nodeB, that's to say all the old IOs from nodeA should
    be discarded by the beckend. To do this maybe we should add one new feature like Ceph's watcher and blacklist.

Then how does Ceph's watcher and blacklist work like? In short:
Firstly, all the tcmu nodes should register a watcher to the Ceph cluster.
Secondly, the ceph cluster will watch all the tcmu nodes and check the health of them.
Lastly, if any of the nodes is died or something wrong, the ceph cluster will add the node to blacklist and then forbid any operation from it before it is removed from the blacklist.

**Comment by amarts** [comment] 2018-06-19 06:12
## Proposal
More thoughts on how to do it in [glusterfs](gluster/glusterfs) project. 

Feel free to add comments and possibilities and options, or discard the whole idea.

### Assumptions:

* All gluster-block files would be served from a gluster volume specially created for gluster-block consumptions. ie, it can have a separate volume type of its own in future. For now, only gluster-block profile gets applied.
* No expansion of block volume (ie, no add-brick), but we would create another volume if we are running out of space.

### New way of locking

ALUA feature itself, or fencing in general doesn't ask us to use the 'locks' as the basic primitive. It is left to the implementations to provide this behavior.

We will be dependent on making sure 'open()' and 'close()' from higher layers as the indication for a block file being in use and getting released respectively. Which means, we shouldn't allow another open() from different clients.

Now, easiest way of implementing it in glusterfs is to write 2 new translators, one at the top of of client graph, which implements mostly just 'open()' and 'close()'/'release()' fops.. the second one just on top of posix layer on brick graph, which can handle and understand the difference between open() from actual client Vs open from client protocol reconnects, and self-heal opens. That way, it can prevent the open all together.  Server side xlator can keep a counter per file, which can get incremented for every successful open (a generation number), and can be persisted on backend in the xattr structure. Client should send this generation number for which it is sending 'open()' all the time, so a open can be prevented if a file was open during n/w disruption, and we allowed the open() from other nodes.

This way, we don't need to do the 'locking()' fops change, but can handle the open() to close() consistency, and can be later extend it to use-cases like hyperconverged etc. Happy to discuss more on this.

@pranithk @pkalever @ShyamsundarR @KritikaDhananjay @raghavendrabhat @xhernandez

**Comment by ShyamsundarR** [comment] 2018-06-27 16:52
The logic of preventing access by another client using open restrictions sounds fine.

The use of generation numbers to address detection of stale client reopening also sounds fine.

The problem that I see with this mechanism, is the assumption that the consumer (or client) uses the generation number based approach to notify Gluster about a reopen of the backing file (Guster stack itself reopening the fd on the consumers behalf is one part of the flow, that we can auto handle). IOW, how is a gen# tied to a consumers instance? and, how will this survive an attempt to reopen the backing file by the consumer? As this can be misread as a new open and hence allowed with a higher gen#.
NOTE: Consumer here is, say, TCMU

If I read the comment that opened this issue by @lxbsz, and in particular this line,
"5, If every thing is okay in nodeB, then the path will be switched to nodeB, that's to say all the old IOs from nodeA should be discarded by the beckend. To do this maybe we should add one new feature like Ceph's watcher and blacklist."

The understanding is that nodeA may attempt to replay its (now) stale IO and this has to be rejected by the Gluster stack, till nodeA is cleared up. Essentially some form of a blacklist.

Assuming we continue with a blacklist option and with the (fd+gen#), a reopen by the consumer should preserve the gen # that was used.

When will this gen# lose its affinity to the consumer? IOW, What are the rules here that the the consumer needs to play by to ensure we do not misinterpret a reopen as either a stale open or actually a clean open.

NOTE: One of the assumption in the above discussion is that there are currently no active opens against the backing file from nodeB or otherwise, for any reason, as a result the timeout does not kick in.

If we arrive at clear rules that the consumer needs to play by, then extending this framework (or even the lock based framework) we can actually use the gen# as an out of band communication to the consumer to notify that it has stale data that needs to be dropped, and avoid the blacklist functionality altogether. This would be a good feature to have IMO.

If the client has to code to a rules of engagement, then avoiding the blacklist can also be a part of the contract.

**Comment by pkalever** [comment] 2018-09-28 13:11
Updated my comments at:
https://github.com/gluster/glusterfs/issues/466#issuecomment-425428654

**Comment by pkalever** [comment] 2018-09-28 13:17
> 5, If every thing is okay in nodeB, then the path will be switched to nodeB, that's to say all the old IOs from nodeA should be discarded by the beckend. To do this maybe we should add one new feature like Ceph's watcher and blacklist.

@lxbsz 
As discussed at meeting, if we can just enforce like,
* only the lock owner should be allowed to read/write the backend file and any read/write requests arriving from the non-lock-owner should be simply discarded/failed by glusterfs.

Given glusterfs behave this manner, we don't need any blacklist or watcher right ?

**Comment by spalai** [comment] 2018-09-28 14:41
> > 5, If every thing is okay in nodeB, then the path will be switched to nodeB, that's to say all the old IOs from nodeA should be discarded by the beckend. To do this maybe we should add one new feature like Ceph's watcher and blacklist.
> 
> @lxbsz
> As discussed at meeting, if we can just enforce like,
> 
> * only the lock owner should be allowed to read/write the backend file and any read/write requests arriving from the non-lock-owner should be simply discarded/failed by glusterfs.
> 
> Given glusterfs behave this manner, we don't need any blacklist or watcher right ?

Agree with Prasanna here. The locking mechanism fits here quite right. All we need to do is implement a lock revocation api from gfapi. And tcmu-runner can choose to revoke as it wants. Mandatory lock implementation is already there. Tcmu would need to take full file mandatory lock until is unlocked by the same client or revoked by another.

**Comment by lxbsz** [comment] 2018-09-29 03:08
> > 5, If every thing is okay in nodeB, then the path will be switched to nodeB, that's to say all the old IOs from nodeA should be discarded by the beckend. To do this maybe we should add one new feature like Ceph's watcher and blacklist.
> 
> 
> @lxbsz
> As discussed at meeting, if we can just enforce like,
> 
> only the lock owner should be allowed to read/write the backend file and any read/write requests arriving from the non-lock-owner should be simply discarded/failed by glusterfs.
> Given glusterfs behave this manner, we don't need any blacklist or watcher right ?

Yeah, right, I just listed the blacklist feature just wanted to have simple and showed what the ceph was doing. In gluster we could just borrow what we need.

**Comment by ShyamsundarR** [comment] 2018-10-03 17:44
> > > 5, If every thing is okay in nodeB, then the path will be switched to nodeB, that's to say all the old IOs from nodeA should be discarded by the beckend. To do this maybe we should add one new feature like Ceph's watcher and blacklist.
> > 
> > 
> > @lxbsz
> > As discussed at meeting, if we can just enforce like,
> > only the lock owner should be allowed to read/write the backend file and any read/write requests arriving from the non-lock-owner should be simply discarded/failed by glusterfs.
> > Given glusterfs behave this manner, we don't need any blacklist or watcher right ?
> 
> Yeah, right, I just listed the blacklist feature just wanted to have simple and showed what the ceph was doing. In gluster we could just borrow what we need.

For Gluster to discard IOs from node-A, it needs to know that node-A does not hold the lock anymore, this is achieved by the lock breaking done by node-B, after which Gluster knows node-A is no longer authoritative and node-B holds the lock.

Now, what prevents node-A from retaking the lock, in 2 scenarios, breaking the lock that node-B has acquired, or assume node-B relinquished the lock and hence no-one owns it anymore?

The above is where I think blacklist comes into picture, to establish the fact that node-A needs to have its state cleaned up and then white listed. OR we do it without blacklists, if the service (tcmu-runner in this case) realizes that it is attempting to retake an older version/generation of the lock.

Below is one method for the same (i.e using generation numbers on the lock), there could be others:
If the runner, or node-A, realizes it has pending IOs and for whatever reason recovers, it should,
- Try the IO
- Get a failure on the IO that it does not hold the lock anymore (in either scenarios, node-B has a lock, or no-one has the lock as it was granted and later released by node-B)
- Attempt to retake the lock, with the same generation#
- Succeed, in which case no other runner/service took the lock in between and it was merely garbage collected or gluster restarted, and continue
- Fail, and realize that it has stale data/session and drop all state (IO buffers, connections to initiators or what not, that makes sense to not replay stale IO), and recover from there

**Comment by lxbsz** [comment] 2018-10-08 09:51
> > > > 5, If every thing is okay in nodeB, then the path will be switched to nodeB, that's to say all the old IOs from nodeA should be discarded by the beckend. To do this maybe we should add one new feature like Ceph's watcher and blacklist.
> > > 
> > > 
> > > @lxbsz
> > > As discussed at meeting, if we can just enforce like,
> > > only the lock owner should be allowed to read/write the backend file and any read/write requests arriving from the non-lock-owner should be simply discarded/failed by glusterfs.
> > > Given glusterfs behave this manner, we don't need any blacklist or watcher right ?
> > 
> > 
> > Yeah, right, I just listed the blacklist feature just wanted to have simple and showed what the ceph was doing. In gluster we could just borrow what we need.
> 
> For Gluster to discard IOs from node-A, it needs to know that node-A does not hold the lock anymore, this is achieved by the lock breaking done by node-B, after which Gluster knows node-A is no longer authoritative and node-B holds the lock.
> 
> Now, what prevents node-A from retaking the lock, in 2 scenarios, breaking the lock that node-B has acquired, or assume node-B relinquished the lock and hence no-one owns it anymore?
> 

There is one scenario in my mind from what the current code is doing in tcmu-runner:

We should make sure that at any time the lock hold by old owner could be broken by others and released by itself.

When the new node is acquiring the lock, it will register one owner entity to the gluster file's owner list(for our case the owner list will have only one member at any time), and one TAG will be generated, which likes <DATA/TIME NODEX> for example,  and for each IO it will also contain the lock TAG when inserting it to the gluster file IO  waiting queue(if there has one).  The TAG could be visible for the NODEX or not, it depends.

> The above is where I think blacklist comes into picture, to establish the fact that node-A needs to have its state cleaned up and then white listed. OR we do it without blacklists, if the service (tcmu-runner in this case) realizes that it is attempting to retake an older version/generation of the lock.
> 

For each IO when being executed it will check its TAG with the current lock owner's,  then discard it if not match. That means once the lock is broken the old IOs should be discarded/failed by gluster file to prevent corrupting the data.


> Below is one method for the same (i.e using generation numbers on the lock), there could be others:
> If the runner, or node-A, realizes it has pending IOs and for whatever reason recovers, it should,
> 
> * Try the IO
> * Get a failure on the IO that it does not hold the lock anymore (in either scenarios, node-B has a lock, or no-one has the lock as it was granted and later released by node-B)
> * Attempt to retake the lock, with the same generation#

Do you mean the IO in node-A will retake the lock when it find node-A is not holding the lock? 

Here is just one case:
1, node-A has one Write IO, let call it WRITE-A0 block for a very long time for some reason.
2, node-B acquire the lock and then update the gluster file at the same offset with the WRITE-A0, then the node-B release the lock for some reason, such as node-C try to successfully break the lock but failed to acquire the lock, then there won't have any lock owner.
3, in node-A the WRITE-A0 working again, it acquire the lock successfully and will corrupt the data.

Will this make sense ?

Thanks,

> * Succeed, in which case no other runner/service took the lock in between and it was merely garbage collected or gluster restarted, and continue
> * Fail, and realize that it has stale data/session and drop all state (IO buffers, connections to initiators or what not, that makes sense to not replay stale IO), and recover from there

**Comment by ShyamsundarR** [comment] 2018-10-09 13:43
> > > > > 5, If every thing is okay in nodeB, then the path will be switched to nodeB, that's to say all the old IOs from nodeA should be discarded by the beckend. To do this maybe we should add one new feature like Ceph's watcher and blacklist.
> > > > 
> > > > 
> > > > @lxbsz
> > > > As discussed at meeting, if we can just enforce like,
> > > > only the lock owner should be allowed to read/write the backend file and any read/write requests arriving from the non-lock-owner should be simply discarded/failed by glusterfs.
> > > > Given glusterfs behave this manner, we don't need any blacklist or watcher right ?
> > > 
> > > 
> > > Yeah, right, I just listed the blacklist feature just wanted to have simple and showed what the ceph was doing. In gluster we could just borrow what we need.
> > 
> > 
> > For Gluster to discard IOs from node-A, it needs to know that node-A does not hold the lock anymore, this is achieved by the lock breaking done by node-B, after which Gluster knows node-A is no longer authoritative and node-B holds the lock.
> > Now, what prevents node-A from retaking the lock, in 2 scenarios, breaking the lock that node-B has acquired, or assume node-B relinquished the lock and hence no-one owns it anymore?
> 
> There is one scenario in my mind from what the current code is doing in tcmu-runner:
> 
> We should make sure that at any time the lock hold by old owner could be broken by others and released by itself.
> 
> When the new node is acquiring the lock, it will register one owner entity to the gluster file's owner list(for our case the owner list will have only one member at any time), and one TAG will be generated, which likes <DATA/TIME NODEX> for example, and for each IO it will also contain the lock TAG when inserting it to the gluster file IO waiting queue(if there has one). The TAG could be visible for the NODEX or not, it depends.
> 
> > The above is where I think blacklist comes into picture, to establish the fact that node-A needs to have its state cleaned up and then white listed. OR we do it without blacklists, if the service (tcmu-runner in this case) realizes that it is attempting to retake an older version/generation of the lock.
> 
> For each IO when being executed it will check its TAG with the current lock owner's, then discard it if not match. That means once the lock is broken the old IOs should be discarded/failed by gluster file to prevent corrupting the data.

Overall a TAG that identifies staleness of the IO/lock is a useful approach.

Who is checking the TAG for staleness here? Gluster or tcmu? Based on which the design needs to evolve appropriately.

> 
> > Below is one method for the same (i.e using generation numbers on the lock), there could be others:
> > If the runner, or node-A, realizes it has pending IOs and for whatever reason recovers, it should,
> > 
> > * Try the IO
> > * Get a failure on the IO that it does not hold the lock anymore (in either scenarios, node-B has a lock, or no-one has the lock as it was granted and later released by node-B)
> > * Attempt to retake the lock, with the same generation#
> 
> Do you mean the IO in node-A will retake the lock when it find node-A is not holding the lock?

Yes, Node-A has pending IO, and no lock (or gets a lock error) and tries to recover its held lock.

> 
> Here is just one case:
> 1, node-A has one Write IO, let call it WRITE-A0 block for a very long time for some reason.
> 2, node-B acquire the lock and then update the gluster file at the same offset with the WRITE-A0, then the node-B release the lock for some reason, such as node-C try to successfully break the lock but failed to acquire the lock, then there won't have any lock owner.
> 3, in node-A the WRITE-A0 working again, it acquire the lock successfully and will corrupt the data.
> 
> Will this make sense ?

Yes.

2 things can happen, tcmu on node-A may not retake the lock, but just fail, or attempt a recovery. If the latter happens then corruptions can occur, else we should be fine IMO.

Overall I think the scenario of stale IO from a stale tcmu is understood, solutions can evolve as the problem is now shared I believe.

> 
> Thanks,

Thanks for your patience as well in following through this reasoning.

> 
> > * Succeed, in which case no other runner/service took the lock in between and it was merely garbage collected or gluster restarted, and continue
> > * Fail, and realize that it has stale data/session and drop all state (IO buffers, connections to initiators or what not, that makes sense to not replay stale IO), and recover from there

**Comment by lxbsz** [comment] 2018-10-10 02:16
> > 
> > For each IO when being executed it will check its TAG with the current lock owner's, then discard it if not match. That means once the lock is broken the old IOs should be discarded/failed by gluster file to prevent corrupting the data.
> 
> Overall a TAG that identifies staleness of the IO/lock is a useful approach.
> 
> Who is checking the TAG for staleness here? Gluster or tcmu? Based on which the design needs to evolve appropriately.

I am afraid we must do this in Gluster, there have at least 3 cases that will lead the data corruption:
Case1: the stale IOs are already pended in Gluster from node-A, and later the lock is broken by node-B, after node-B already update that data the stale IOs are woken up and update the same data again, then these stale IOs won't under the control by tcmu.

Case2: the stale IOs are pended on the way to Gluster backend from node-A, such as if the Gluster backend and the tcmu service are not in the same node, the stale IOs could be pended by the network ..., then it will be the same with Case1.

Case3: the stale IOs are pended in the tcmu service side, such as the ringbuffer queue. Then in tcmu-runner just before sending them to Gluster we can have a way to check the lock TAG and then discard/fail them. 

Thanks,
BRs

**Comment by spalai** [comment] 2018-10-10 07:01
> > > For each IO when being executed it will check its TAG with the current lock owner's, then discard it if not match. That means once the lock is broken the old IOs should be discarded/failed by gluster file to prevent corrupting the data.
> > 
> > 
> > Overall a TAG that identifies staleness of the IO/lock is a useful approach.
> > Who is checking the TAG for staleness here? Gluster or tcmu? Based on which the design needs to evolve appropriately.
> 
> I am afraid we must do this in Gluster, there have at least 3 cases that will lead the data corruption:
> Case1: the stale IOs are already pended in Gluster from node-A, and later the lock is broken by node-B, after node-B already update that data the stale IOs are woken up and update the same data again, then these stale IOs won't under the control by tcmu.
> 
> Case2: the stale IOs are pended on the way to Gluster backend from node-A, such as if the Gluster backend and the tcmu service are not in the same node, the stale IOs could be pended by the network ..., then it will be the same with Case1.
> 
> Case3: the stale IOs are pended in the tcmu service side, such as the ringbuffer queue. Then in tcmu-runner just before sending them to Gluster we can have a way to check the lock TAG and then discard/fail them.
> 
> Thanks,
> BRs

Agreed to the approach of adding lock tags to IOs. This will help server identifying stale IOs and further, it can mark corresponding client fd as BAD. 

I guess we will have to do tag checking at server side on Gluster. Once the IOs are cached by Gluster, I am afraid that tcmu will have any control over discarding them.

**Comment by lxbsz** [comment] 2018-10-10 07:42
> I guess we will have to do tag checking at server side on Gluster. Once the IOs are cached by Gluster, I am afraid that tcmu will have any control over discarding them.

will --> won't ?
If so, yeah, agree.

**Comment by spalai** [comment] 2018-10-10 09:00
> > I guess we will have to do tag checking at server side on Gluster. Once the IOs are cached by Gluster, I am afraid that tcmu will have any control over discarding them.
> 
> will --> won't ?
> If so, yeah, agree.

Yes, will->won't.

**Comment by ShyamsundarR** [comment] 2018-10-10 13:21
> > > I guess we will have to do tag checking at server side on Gluster. Once the IOs are cached by Gluster, I am afraid that tcmu will have any control over discarding them.
> > 
> > 
> > will --> won't ?
> > If so, yeah, agree.
> 
> Yes, will->won't.

Clarifying as there are 2 will's in the statement: "I guess we will have to do tag checking at server side on Gluster. Once the IOs are cached by Gluster, I am afraid that tcmu **won't** have any control over discarding them."

**Comment by pkalever** [comment] 2018-10-23 10:57
@lxbsz @ShyamsundarR @spalai @amarts This model looks good to me. Thanks!

**Comment by lxbsz** [comment] 2018-10-23 13:03
> @lxbsz @ShyamsundarR @spalai @amarts This model looks good to me. Thanks!

Cool, Looks good to me too.

**Comment by spalai** [comment] 2018-10-24 06:58
Alright. Just summarizing here with all the points mentioned above, followed by some technical details.

**Problem**:  The problem we are trying to solve here is to have a single dedicated access to glusterfs from one tcmu-runner instance at a time.
   To handle failover for a connection problem on the initial node (call it node-A)(be it a connection problem between glusterfs to tcmu-runner
on node-A or tcmu-runner(& node-A) crashing or rebooting) or a resource crunch, gluster-block rely on MULTI-PATH, where the INITIATOR
switches over to a different tcmu-runner instance running on a different host (call it node-B),

To summarize, we want to prevent any operation from node-A if the INITIATOR has switched over it's operations to node-B.(or vice-versa)

**Solution**: From various discussions and meetings we have arrived at a solution where each tcmu-runner will be able to operate on the file
if and only if it has a mandatory lock on the file. And for this, we need a way to break the lock as well for the INITIATOR to be able to switch
to a different tcmu-runner instance. Here are the various possible scenarios for breaking the lock.

**case - 1**: Connection between server and client goes down.
     
   Post ping-timeout, the server will clean up the locks associated with the fd opened by node-A. And a safe switch-over can happen over to node-B.

**case - 2**: Connection between tcmu-runner on node-A and INITIATOR goes down.
    
   Post timeout, INITIATOR will switch to node-B. Here the connection between node-A and glusterfs is still intact. Hence, we need a lock revoking API(this will need some mechanism to have a single  dedicated lock-owner for all tcmu-runner, more to this later).   Once node-B lock acquisition successful, all pending fops or incoming fops from node-A will be discarded, upon which the connection should be
closed to glusterfs from tcmu-runner running on node-A.

**case - 3**: Node-A tries to reconnect with glusterfs and replays pending IO from an outdated session. (Pointed out by Shyam)
  **Two scenarios possible here:** 
   **3.1**: A temporary disconnection leads to locks being cleaned up. node-A can reattempt to take the lock and succeeds in case nobody else   has taken the lock.
   
   **3.2:** Post disconnection a switchover happens to node-B. Now if node-B still holds the lock, node-A will see a failure in the attempt to the lock. Or if node-B has relinquished the lock, then node-A will be able to take the lock and replay pending IOs which might lead to corruption.

For this, we need to tag a generation number with each lock. So that when node-A tries to attempt locking with old generation number, the lock request can be discarded and hence, any further operations.  For this, we need to have one generation number per one session (open to close                operation on the file from a single tcmu-runner). [The technical challenge here is the coordination between different nodes for the generation number]


The following would be required from GlusterFS.

 **1 - A mechanism to preempt lock**: This will help INITIATOR to switch to a different tcmu-runner instance from the current one to operate safely on the file. This will be a exposed as a gfapi.

 **2-  A server translator to generate a session id dedicated for one specific tcmu-runner:**
 This is for case 3.2 where INITIATOR has moved to node-B from node-A post some issues on node-A. We need to avoid the scenario where node-B has reliquished the lock and then node-A is trying to replay some fops. 

**How it works?** tcmu-runner will open a session post taking a mandatory lock. The session creation will be through a gfapi. Upon this request, the server xlator will associate the fd with a unique id. Most likely this would be "epoch time" since epoch time is never constant.  Now for any request from node-A with the above scneario will be rejected since node-A requests will come through the old epoch time.

For any network disconnection, tcmu-runner is expected to take mandatory lock again(locks get cleaned up post disconnection) followed by opening a new session.

The request sequence from tcmu-runner:
 - fd = open (file);
 - glfs_lock_revoke (fd);
 - fcntl (fd, mandatory lock); 
 - glfs_opensession (fd); *This will be stored by a client xlator as well*
 ...... (regular ops)
 - close (fd).

The server translator will be place above lock translator.
 
**3 - **A client translator to tag each fop with the unique id**:**
 Keep track of id generated by server and tag with all incoming fops. 
 This translator will most likely be place above AFR.

This is the general view of the new functionalities. 

Please add your feedback on the this. 

@pkalever @lxbsz We need to implement the above measures to avoid scenario 3.2 where fop replay can happen post a mandatory lock release from a different client. Now is it possible to avoid this scneario from tcmu-runner side? I mean, can INITIATOR short of shutdown tcmu-runner instance on node-A if it has already switched to node-B? With this, we would not need to implement 2 and 3. 

Let us know your input.

Thanks,
Susant

**Comment by lxbsz** [comment] 2018-10-24 08:14
> @pkalever @lxbsz We need to implement the above measures to avoid scenario 3.2 where fop replay can happen post a mandatory lock release from a different client. Now is it possible to avoid this scneario from tcmu-runner side? I mean, can INITIATOR short of shutdown tcmu-runner instance on node-A if it has already switched to node-B? With this, we would not need to implement 2 and 3.
> 

I am afraid not, the multipath service will keeping trying to re-establish the connection/session to node-A after disconnection happens. If the node-A is the active path node, the path will fallback once it's available.

**Comment by spalai** [comment] 2018-10-25 05:55
> > @pkalever @lxbsz We need to implement the above measures to avoid scenario 3.2 where fop replay can happen post a mandatory lock release from a different client. Now is it possible to avoid this scneario from tcmu-runner side? I mean, can INITIATOR short of shutdown tcmu-runner instance on node-A if it has already switched to node-B? With this, we would not need to implement 2 and 3.
> 
> I am afraid not, the multipath service will keeping trying to re-establish the connection/session to node-A after disconnection happens. If the node-A is the active path node, the path will fallback once it's available.

Alright, that will leave us with all 3 requirements. I will start working on this and will update when the patches are ready.

**Comment by soumyakoduri** [comment] 2018-10-26 10:52
> **case - 2**: Connection between tcmu-runner on node-A and INITIATOR goes down.
> 
> Post timeout, INITIATOR will switch to node-B. Here the connection between node-A and glusterfs is still intact. Hence, we need a lock revoking API(this will need some mechanism to have a single dedicated lock-owner for all tcmu-runner, more to this later). Once node-B lock acquisition successful, all pending fops or incoming fops from node-A will be discarded, upon which the connection should be
> closed to glusterfs from tcmu-runner running on node-A.

My two cents -

In general by revocation() word, the assumption is that something which server does (lock/state revocation etc)  when client misbehaves or doesnt respond but not done by another client. 
 WRT the functionality which is being described here as missing, we had had discussions about the same in past for multi-protocol and HA support and we used to refer to it as reclaim_lock(..).

Design discussions can be found below -
https://review.gluster.org/#/c/glusterfs-specs/+/15053/

So what we were trying to achieve is that , when nodeA (gfapi clientA) goes down and fails over to nodeB (gfapi clientB), nodeB sends reclaim_lock request same as original posix/madatory_lock request but with a flag marking it as a reclaim request.

On the server-side, glusterfs lk xlator does conflict checks based on client-id+lk_owner. But on receiving reclaim_lk request, it relaxes that check , which means it checks for only lk-owner and updates the client-id to the nodeB client-id. 

This way, nodeB can reclaim the original lk by a single request and can avoid multiple round-trips (to first revoke, and then re-send lock request). Thoughts?

**Comment by soumyakoduri** [comment] 2018-10-26 10:56
Not to mention in between client2's lock revocation and lock request, there are chances that other third client can acquire lock which can be avoided from reclaim lock.

**Comment by spalai** [comment] 2018-10-26 11:32
@soumyakoduri Have posted a patch here https://review.gluster.org/#/c/glusterfs/+/21496/ which does in fact as you mentioned the lk-owner|clientid and sends an unlock request. We can actually merge the getlk and updating of client id|lk-owner.

**Comment by pkalever** [comment] 2021-06-10 11:47
Won't Fix, closing now.

**Closed by pkalever** 2021-06-10 11:47 UTC
Labels: GCS/Blocker, GCS/v1.0, enhancement
