### ISSUE TITLE
gluster-blockd crash when creating/deleting the block devices

### ISSUE THREAD

**Issue by lxbsz** [gluster/gluster-block#78] opened 2018-04-17 04:27 UTC
How to reproduce:

$ while [ 1 ]; do gluster-block create dht0/block23 ha 1 192.168.195.134 1G; sleep 2;  gluster-block delete dht0/block23; sleep 1; done

How often:

Till now only once for 2 hours.

The crash logs:

Apr 16 23:42:32 gblock2 systemd[1]: gluster-blockd.service failed.
Apr 16 23:42:32 gblock2 systemd[1]: Unit gluster-blockd.service entered failed state.
Apr 16 23:42:32 gblock2 systemd[1]: gluster-blockd.service: main process exited, code=killed, status=11/SEGV
Apr 16 23:42:32 gblock2 kernel: gluster-blockd[2685]: segfault at 0 ip 00000000004198f0 sp 00007fe3b572dc80 error 4 in gluster-blockd[400000+32000]
[gluster-block-cli.log](https://github.com/gluster/gluster-block/files/1918129/gluster-block-cli.log)
[gluster-block-configshell.log](https://github.com/gluster/gluster-block/files/1918130/gluster-block-configshell.log)
[Uploading gluster-blockd.log…]()
[Uploading gluster-block-gfapi.log…]()
[Uploading tcmu-runner.log…]()
[Uploading tcmu-runner-glfs.log…]()

**Comment by ahmadou** [comment] 2018-05-24 08:43
Hi i'm also experiencing the same issue.

```
May 24 10:40:05 storage01 kernel: gluster-blockd[94722]: segfault at 0 ip 00000000004198f0 sp 00007fb122eecc80 error 4 in gluster-blockd[400000+32000]
May 24 10:40:05 storage01 systemd: gluster-blockd.service: main process exited, code=killed, status=11/SEGV

```
So far the block provisionning has been working but suddenly it started behaving randomly and now is completely broken.

**Comment by lxbsz** [comment] 2018-06-05 10:53
@ahmadou 

What version you are using for glsuter-blockd ? Upstream version ?

Thanks,

**Comment by ahmadou** [comment] 2018-06-05 10:56
Hi, 

I built it from the master branch

**Comment by lxbsz** [comment] 2018-06-05 11:04
@ahmadou 

Okay, that's to say this bug also is exist in the master.
Thanks very much.

**Comment by pkalever** [comment] 2018-11-23 07:34
@lxbsz did we already fix this ?

**Comment by lxbsz** [comment] 2018-11-23 07:40
I only hit once, then tried tens of times hasn't reproduce it yet till now.

**Comment by pkalever** [comment] 2019-04-02 10:54
We tried this enough and still couldn't reproduce this with our latest master.

There are lot many stability fixes went in latest master since a while.
As we couldn't reproduce this with our decent testing efforts, closing this as fixed by misc patches.

When you hit this next time, please do attach the coredump or backtrace.

Many thanks for reporting.

**Closed by pkalever** 2019-04-02 10:54 UTC
